<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "addressmgmt"
 *
 * Auto generated by Extension Builder 2013-09-17
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Address Management',
	'description' => 'Keep track of all types of addressable records',
	'category' => 'plugin',
	'author' => 'Felix Althaus, Eike Starkmann',
	'author_email' => 'felix.althaus@undkonsorten.com, eike.starkmann@undkonsorten.com',
	'author_company' => 'undkonsorten, undkonsorten',
	'state' => 'stable',
	'version' => '6.0.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '11.5.0-12.99.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
            "femanager" => "7.0.0-7.99.99"
		),
	),
);
