<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "addressmgmt"
 *
 * Auto generated by Extension Builder 2013-09-17
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Address Management',
	'description' => 'Keep track of all types of addressal records',
	'category' => 'plugin',
	'author' => 'Felix Althaus, Eike Starkmann',
	'author_email' => 'felix.althaus@undkonsorten.com, eike.starkmann@undkonsorten.com',
	'author_company' => 'undkonsorten, undkonsorten',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '3.1.3',
	'constraints' => array(
		'depends' => array(
			'typo3' => '8.7.0-8.99.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
            "femanager" => "4.2.0-4.9.99"
		),
	),
);

?>
